### ISSUE TITLE
Saved JS files sourced from Dist

### ISSUE THREAD

**Issue by jazzyclimber** [iGoMoon/hubspot-fields-js#2]
I have a patch for this here: https://github.com/jazzyclimber/hubspot-fields-js/blob/main/src/plugins/FieldsPlugin.js

The plumbing is all set and ready to go. No infinite upload loop. No .env file needed.

This afternoon I was only able to get the plumbing set. So currently it uploads all fields.js files on save. Which I suppose isnt really an issue. But it's not expected from a user perspective. Either way it shouldnt be too difficult to make it so that it's only the saved file that is uploaded. 

I can likely tackle this extra fix this weekend/early next week. 

Posted this to @frankfava On HS Slack. Reposted here to follow guidelines for contribution. 

If you dig the edits and direction let me know and ill make a PR!

-- BJ

**Comment by frankfava-IGM** [comment]
Hey Beej, 

Not sure if you got a chance to update this since we spoke, but I'll repost it here

> We cant really do `let fullDistPath = file.replace("/src/", '/dist/')` the copyWebpack Plugin means that src and dist dont necessarily have the same structure.

If you update that and then create PR, we'll get into the source :D

Cheers man

**Comment by jazzyclimber** [comment]
Hey Frank!

Finally got around to updating the original PR. 

This was actually a bit more challenging than I had originally expected. Im sure that there is a more webpack way to do this. But I couldnt find any docs or info on where webpack stored output info from copyWebpackPlugin.

So I ended up doing a bunch of logging until I found that compilation.emittedAssets actually contained paths to the emitted assets which honored the folder structure set in webpack.config. 

Let me know if you have any questions!

https://github.com/iGoMoon/hubspot-fields-js/pull/3

-BJ

**Comment by frankfava-IGM** [comment]
Awesome man, Love it, I'll dive into this over the break. If we can get that solve it'll be great!

**Comment by jazzyclimber** [comment]
Sweet deal! Sounds good!

**Comment by frankfava-IGM** [comment]
@jazzyclimber Love your work, added in with v1.2.0
https://github.com/iGoMoon/hubspot-fields-js/commit/49f843abd722877d94a3ccee18a30f13a6163c3b
